# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ???
  # name: ${name}
  save_dir: "${paths.output_dir}"
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  # entity: ""  # set to name of your wandb team
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  job_type: "train"
  group: ""
  tags: []
