log_example_image_fakeReg_B:
  _target_: cmrai.utils.my_callbacks.LogExampleImages
  name: "img/A2B-Reg"
  image_list: ["real_A", "real_B", "reg_fake_B"] # name of last images is used to save the images
  output_dir: ${paths.output_dir}
  log_train_img_interval: ${eval:10_000 // ${global_batch_size}}
  log_val_img_interval: ${eval:1_000 // ${global_batch_size}}
